### ISSUE TITLE
duplication of work?

### ISSUE THREAD

**Issue by mrkafk** [michaelfairley/mincemeatpy#10]
It seems that shepherd is handing over the same piece of work to multiple workers?

Minimally modified example.py:

http://dpaste.com/hold/1501864/

Then I ran shepherd this way:

% python shepherd.py -n 3 -8
map K 1 map V Humpty Dumpty had a great fall PID 25153
map K 0 map V Humpty Dumpty sat on a wall PID 25152
map K 2 map V All the King's horses and all the King's men PID 25153
map K 3 map V Couldn't put Humpty together again PID 25152
map K 3 map V Couldn't put Humpty together again PID 25153
reduce k a vs: [1, 1] PID 25152
reduce k on vs: [1] PID 25153
reduce k great vs: [1] PID 25152
reduce k Humpty vs: [1, 1, 1] PID 25153
reduce k all vs: [1] PID 25152
reduce k wall vs: [1] PID 25153
reduce k Dumpty vs: [1, 1] PID 25152
reduce k King's vs: [1, 1] PID 25153
reduce k men vs: [1] PID 25152
reduce k had vs: [1] PID 25153
reduce k All vs: [1] PID 25152
reduce k together vs: [1] PID 25153
reduce k and vs: [1] PID 25152
reduce k horses vs: [1] PID 25153
reduce k Couldn't vs: [1] PID 25152
reduce k fall vs: [1] PID 25153
reduce k put vs: [1] PID 25152
reduce k again vs: [1] PID 25153
reduce k the vs: [1, 1] PID 25152
reduce k sat vs: [1] PID 25153
reduce k sat vs: [1] PID 25152

As you can see, the same piece of work was handed over to more than 1 worker. Does this work as designed?

**Comment by michaelfairley** [comment]
Yep! This is done intentionally. Section 3.6 (Backup Tasks) of the [MapReduce paper](http://static.googleusercontent.com/media/research.google.com/en/us/archive/mapreduce-osdi04.pdf) discusses this a bit, and it will often make multi-machine jobs finish more quickly.

**Comment by mrkafk** [comment]
Thanks! Although in peculiar case I'm handling this is a downside...
