### ISSUE TITLE
A new implementation of mincemeatpy using node.js

### ISSUE THREAD

**Issue by denghongcai** [michaelfairley/mincemeatpy#12]
Hi:
I'm interesting in your mincemeatpy, and i think it's useful for sudden, heavy job.So I implementation it using node.js.It's easy to use and make full advantages of node.js's network ability.I also make some improvement.
Can u add my repo into your Readme?Thanks! 
[mincemeat-node](https://github.com/denghongcai/mincemeat-node)

**Comment by michaelfairley** [comment]
@denghongcai Very cool! Unfortunately I don't know enough node to properly look over your code, and I don't feel comfortable endorsing something that I haven't used or reviewed.

**Comment by denghongcai** [comment]
Oh, I forget this.It's fine then.I will develop my own version, thanks again for you python version which help me know more about MapReduce.
