### ISSUE TITLE
Trying to cascade MapReduce

### ISSUE THREAD

**Issue by jpmec** [michaelfairley/mincemeatpy#3]
Hello,

I am trying to cascade MapReduce operations using mincemeatpy.  The solution I tried is to create a Server within a mapfn.  The Server uses a different port than the global Server object.  It doesn't work because asyncore uses a global socket_map object.

So I am trying to pass my own map into asyncore.loop

However, I am having difficulties and it seems to be spiraling out of control.

So my first question:  Using mincemeatpy, how could I cascade MapReduce operations?  Can this be done "out-of-the-box" without any modifications to mincemeatpy?

The goal is to use MapReduce to first send out a filenames to clients.  Each of the first layer clients should open their file, then send chunks of their file to other second layer clients.  The second layer clients should process the lines they receive and send the result back to the first layer clients (note the first layer clients will be acting as MapReduce second layer servers for this).  The first layer clients should collect these results, then reduce and send the final result each file back to the first layer server.

The second question is, if modifications are required, do you have any insight into how/what to modify?

Like I said before, I believe the answer is providing maps to the second layer clients, so they are each using their own socket map and not the global socket map.

If I did not explain myself clearly, or you would like an example, I can provide more details and a simple example.

TIA

**Comment by jpmec** [comment]
A followup on my progress on this.  I believe I have got it to work but it required changing mincemeat.py to pass in a map to asyncore.loop, Server and ServerChannel.  I am going to fork and add my fixes, then submit a pull request for your review.

**Comment by michaelfairley** [comment]
Explicitly setting a map per server sounds like a good approach. This code base is fairly old (and untested! sorry!), so let me know if you have any more questions.

**Comment by jpmec** [comment]
Hi Michael, thanks for the quick comment.  BTW, I love the library, simple and elegant!

I've made a pull request with my changes, I hope you like them :-)

https://github.com/michaelfairley/mincemeatpy/pull/4

I can make any changes you want before the merge.

Also, FYI, your library is being promoted and used in the Coursera course here:

https://www.coursera.org/course/bigdata

So you might be seeing a surge in traffic in the coming weeks/months ;-)

**Comment by jpmec** [comment]
Hi Michael, I also added the ability to have clients run forever, waiting for new servers to start up and connect to them.  This will allow you to create a pool of clients that will service the servers as they are created.  By default, the clients will only run once to maintain default behavior.  You can use the -8 option to run indefinitely.

BTW, you can close this issue since pull request #4 has all the important stuff.

**Comment by jpmec** [comment]
Hi Michael, saw that your getting your smoke test going.  Were you able to use it on the pull request I submitted?  I tested and I believe the original example should still run as expected.  I tried to make sure that all existing functionality was still in place, so no existing users would break.  Let me know if you need any info.
