### ISSUE TITLE
socket.error: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by ldjpr** [michaelfairley/mincemeatpy#5]
I am mew to mincemeat. When I try to run a client after running the server I get this error: socket.error: [Errno 48] Address already in use.

 Basically what I do is:
1. python example.py
2. In another terminal python example.py -p changeme localhost

I am using Snow Leopard 10.6.8

Please advice

Thanks

**Comment by michaelfairley** [comment]
You need to mincemeat.py instead of example.py to run the client: `python mincemeat.py -p changeme localhost`

**Comment by ldjpr** [comment]
oops. thanks
